name = "custom"
n_iterations = 6

[[step]]
name = "spot_x"
fitter = "fwhm"
data_key = "offset_x_amplitude"
target_names = ["spot_x"]

[[step]]
name = "spot_y"
fitter = "fwhm"
data_key = "offset_y_amplitude"
target_names = ["spot_y"]

[[step]]
name = "sr_tbc3"
fitter = "offset"
signal = "phase"
data_key = "offset_x_phase"
target_names = ["Sr_2", "TBC_3"]
spot_key = "spot_x"

[[step]]
name = "sz_tbc1"
fitter = "freq"
signal = "phase"
data_key = "freq_phase"
target_names = ["Sz_2", "TBC_1"]
spot_key = "spot_size"
